---
title: "Natural-host v0.3"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: TRUE
    toc_float: TRUE
    theme: flatly
    highlight: zenburn
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
``` 
 
# Biodiversité {.tabset .tabset-fade .tabset-pills} 
 
<br>

## Donnees naturalistes  {.tabset .tabset-fade}
 
<br>

### Application 
 
<br>

#### Flore : 
 
[PlantNet ](https://plantnet.org/en/)<br>
 
<br>

#### Général : 
 
[Inaturalist](https://www.inaturalist.org/)<br>
 
<br>

#### INPN : 
 
[CardObs](https://cardobs.mnhn.fr/cardObs/auth/login)<br>
 
[OpenObs](https://openobs.mnhn.fr/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Clef d’identification 
 
[Explorer Xper 3](http://explorer.xper3.fr/accueil/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Général 
 
[Depobio](https://depot-legal-biodiversite.naturefrance.fr/)<br>
 
[INPN](https://inpn.mnhn.fr/accueil/index)<br>
 
[Le naturaliste](http://www.lenaturaliste.net/portail/index.php)<br>
 
[Recolnat](https://www.recolnat.org/fr/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Indépendant 
 
<br>

#### Dessin : 
 
[Site de Mathilde Dano](https://scientartistmdano.wordpress.com/)<br>
 
<br>

#### Faune : 
 
[Découvrir la faune – Antoine Csutoros](https://www.decouvrirlafaune.fr/la-bibliotheque-du-naturaliste/)<br>
 
<br>

#### Général : 
 
[Wild World](https://u-g-o.jimdofree.com/)<br>
 
[Zoom-nature](https://www.zoom-nature.fr/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Mondial 
 
[Biodiversity library](https://www.biodiversitylibrary.org/)<br>
 
[GBIF](https://www.gbif.org/)<br>
 
<br>

#### IUCN : 
 
[Accueil - Red list - IUCN](https://www.iucnredlist.org/fr/)<br>
 
[Données spacial IUCN red list](https://www.iucnredlist.org/fr/resources/spatial-data-download)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Montpellier 
 
[Data OREME](https://data.oreme.org/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Ecologie  {.tabset .tabset-fade}
 
<br>

### Plateforme 
 
[EIVE 1.0](https://zenodo.org/record/7534792)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Faune  {.tabset .tabset-fade}
 
<br>

### Annélides 
 
<br>

#### Clef d’identification : 
 
[Clé d'identification des vers de terre](https://ecobiosoil.univ-rennes1.fr/cle-de-determination/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Araignées 
 
[Asfra](https://asfra.fr/)<br>
 
[Piwigo Arachno](https://arachno.piwigo.com/index.php?/categories)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Général 
 
[Quel est cet animal](https://www.quelestcetanimal.com/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Herpétofaune 
 
<br>

#### Général : 
 
[Coronella](http://coronella.free.fr/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Insectes 
 
<br>

#### Général : 
 
[Aramel.free](http://aramel.free.fr/)<br>
 
[Insecte.org](https://www.insecte.org/)<br>
 
[Insectes-net](https://www.insectes-net.fr/index.htm)<br>
 
[Monde des minuscules](https://mondedesminuscules.fr/)<br>
 
<br>

#### Larves : 
 
[Animateur nature – Larves d’insectes](https://www.animateur-nature.com/guide-invertebres/les-larves.php)<br>
 
<br>

#### Myrmécologie : 
 
[Myrmecofourmis](https://www.myrmecofourmis.fr/)<br>
 
<br>

#### Orthoptères : 
 
[ASCETE](https://ascete.org/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Mollusques 
 
<br>

#### Mondial : 
 
[Conchology](https://conchology.be/?t=1)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Oiseaux 
 
<br>

#### Général : 
 
[Oiseaux.net](https://www.oiseaux.net/)<br>
 
[Ornitho.fr](http://www.ornitho.fr/)<br>
 
<br>

#### Jeux : 
 
[Biofotoquiz – Oiseaux](https://www.biofotoquiz.ch/domain/standard/id/3/tab/standard)<br>
 
[Comptage – Mania](https://alsace.lpo.fr/Jeux/Comptage/Comptage.php)<br>
 
[Computerbording](https://www.computerbirding.com/what/cbirding_2018_e.php?PHPSESSID=)<br>
 
[Fotooizo](http://fotooizo.free.fr/jeu3.php)<br>
 
<br>

#### Sons : 
 
[Concerto – LPO Alsace](https://alsace.lpo.fr/Jeux/Concerto/Concerto.php?res=1&Largeur=1047&Hauteur=590)<br>
 
[INPN – Chants des oiseaux](https://inpn.mnhn.fr/jeux/oiseaux/accueil-du-jeu)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Outils faune 
 
[DeepFaune](https://www.deepfaune.cnrs.fr/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Poissons 
 
[Trombinoscope Jean-Marc Charel](http://jean-marc.charel.pagesperso-orange.fr/p_trombinoscope.htm)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Sons 
 
<br>

#### Général : 
 
[Xeno-canto](https://xeno-canto.org/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Flore  {.tabset .tabset-fade}
 
<br>

### Donnees 
 
<br>

#### Comestible : 
 
[Edible Plant Database](https://discovery.dundee.ac.uk/en/datasets/edible-plant-database)<br>
 
<br>

#### Général : 
 
[Boite à outil – Le Plantoscope](https://leplantoscope.fr/2021/03/21/decouvrir-les-plantes-une-boite-a-outils/#:~:text=Le%20site%20Wikiphyto%2C%20qui%20recense%20les%20usages%20m%C3%A9dicinaux,anglais%2C%20la%20base%20de%20donn%C3%A9es%20de%20la%20FDA.)<br>
 
<br>

#### Traits : 
 
[Try](https://www.try-db.org/TryWeb/Home.php)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Général 
 
[FloreAlpes](https://www.florealpes.com/)<br>
 
[Préservons la nature](https://www.preservons-la-nature.fr/)<br>
 
[Sysbio – Plante](http://sysbio.univ-lille1.fr/fiches/plantae)<br>
 
[Tela-botanica](https://www.tela-botanica.org/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Outils flore 
 
[API plantnet](https://my.plantnet.org/usage)<br>
 
[E-FLORA-sys](https://eflorasys.univ-lorraine.fr/index.php/fr/pages/display/liens)<br>
 
[Flore en Ligne](http://flore-en-ligne.fr/)<br>
 
[Floristic](http://floristic.org/)<br>
 
[Global Tree Search](https://tools.bgci.org/global_tree_search.php)<br>
 
[Glossaire botanique](https://fr.wikipedia.org/wiki/Glossaire_de_botanique)<br>
 
[Herbier MNHN](https://science.mnhn.fr/institution/mnhn/collection/p/item/search/form)<br>
 
[Plantnet identification la Réunion](https://identify.plantnet.org/fr/reunion/identify)<br>
 
[PlantUse](https://uses.plantnet-project.org/fr/Accueil)<br>
 
[ThePlantGame](http://theplantgame.com/login/?next=/)<br>
 
<br>

#### Analyse : 
 
[Quantitative Plant](https://www.quantitative-plant.org/)<br>
 
<br>

#### Bibliographie : 
 
[Global Plants](https://plants.jstor.org/)<br>
 
[Le trésor de Rémi](https://drive.google.com/drive/folders/15u20P811OIrJzR2eNkAIrRjUhS9e9bd8?usp=sharing)<br>
 
<br>

#### Formation : 
 
[Biologie végétale – UCLouvain](https://biologievegetale.be/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Par groupe 
 
<br>

#### Bryophytes : 
 
[Bryophytes de France - La Réunion](http://bryophytes-de-france.org/yeswiki/wakka.php?wiki=ReuNion)<br>
 
<br>

#### Orchidaceae : 
 
[Clef XPER 3 Orchidées de France](https://orchidees-france.identificationkey.org/mkey.html)<br>
 
[Orchidées en France – durbphil](http://perso.numericable.fr/~durbphil/Ouv2&Listalpha&Pres/sitorchidouv2.htm)<br>
 
[Orchidées Nature](https://www.elisajeanluc.fr/orchidees_nature/index.htm)<br>
 
[Orchids of Britain and Europe](http://www.orchidsofbritainandeurope.co.uk/)<br>
 
[SFO-PCV Société Française d'Orchidophilie de Poitou-Charentes et Vendée](http://www.orchidee-poitou-charentes.org/spip.php?rubrique155)<br>
 
<br>

#### Orobanchaceae : 
 
[Clef Xper 3 des Orobanchaceae des Bouches-du-Rhône](https://www.xper3.fr/xper3GeneratedFiles/publish/identification/-4433262835638514473/mkey.html)<br>
 
<br>

#### Poaceae : 
 
[Botarela](https://botarela.fr/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Photo 
 
[Photoflora](http://www.photoflora.fr/index.php)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Sites complementaires 
 
[Fleurs-fruits-feuilles-de.com](https://fleurs-fruits-feuilles-de.com/galerie_photos.php)<br>
 
[Habiter la Reunion - Flore](https://habiter-la-reunion.re/la-flore-de-la-reunion/)<br>
 
[L’herbier en image – Pierre Goujon](https://abiris.snv.jussieu.fr/flore/herbier.php)<br>
 
[Plante botanique](https://www.plantes-botanique.org/)<br>
 
[Plants of the world online](http://www.plantsoftheworldonline.org/)<br>
 
[PNR - flore](http://www.reunion-parcnational.fr/fr/des-connaissances/la-flore)<br>
 
[Quelle est cette plante](https://quelle-est-cette-fleur.com/)<br>
 
[Quelle est cette plante](https://www.quelleestcetteplante.fr/)<br>
 
[Randopiton - Flore](https://biotope34.sharepoint.com/:x:/s/AgenceDOM/EZ0nw46o1alDiJI3R0F8wfMBjoZClH4kNUVeK2nsR_g-oA?e=LXpM6E)<br>
 
[Thierry Niko 974](http://thierryniko974.over-blog.com/pages/A_LA_DECOUVERTE_DES_ORCHIDEES_DE_LA_REUNION-8836327.html)<br>
 
[Willyplante canalblog](http://willyplante.canalblog.com/archives/endemique_et_indigene_/index.html)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Taxonomie 
 
<br>

#### Flore : 
 
[International Plant Names Index](https://www.ipni.org/)<br>
 
[The Plant List](http://www.theplantlist.org/)<br>
 
[World Flora Online](http://www.worldfloraonline.org/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Usages 
 
<br>

#### Général : 
 
[Floranet : Identification de plantes médicinales et toxiques](https://floranet.pagesperso-orange.fr/)<br>
 
[Plant for a futur](https://pfaf.org/user/Default.aspx)<br>
 
[PlantUse](https://uses.plantnet-project.org/fr/Accueil)<br>
 
[WikiPhyto](http://www.wikiphyto.org/wiki/Accueil)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Fonge  {.tabset .tabset-fade}
 
<br>

### Champignon 
 
<br>

#### Clef d’identification : 
 
[Le Guide des champignons](https://www.guidedeschampignons.com/identification-champignon-un-chapeau-et-un-pied-avec-lamelles/)<br>
 
<br>

#### Général : 
 
[Champis.net](https://champis.net/home)<br>
 
[Mycodb](https://www.mycodb.fr/searchfam.php)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Lichen 
 
[Lichen d’italie](https://italic.units.it/flora/index.php?procedure=ext_key_home&key_id=9352)<br>
 
[Lichen Go – Tela-botanica](https://www.tela-botanica.org/projets/lichens-go/)<br>
 
[Lichen Go – Xper ](http://lichengo.identificationkey.org/mkey.html)<br>
 
<br>

#### Général : 
 
[Association française de Lichénologie](https://www.afl-lichenologie.fr/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Gestion  {.tabset .tabset-fade}
 
<br>

### Général 
 
[Cahier technique des espaces naturels](http://cahiers-techniques.espaces-naturels.fr/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Restauration 
 
[Notice choix arbre - Centre-Val de Loire](https://cbnbp.mnhn.fr/cbnbp/ressources/telechargements/Notice_arbres_arbustes_CBNBP.pdf)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Habitats  {.tabset .tabset-fade}
 
<br>

### Carhab 
 
[CarHab INPN](https://inpn.mnhn.fr/programme/carhab)<br>
 
[Visualisateur Carhab](https://inpn.mnhn.fr/viewer-carto/CarHab/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Eau douce 
 
<br>

#### Général : 
 
[Center for Fresjwater Biology](http://cfb.unh.edu/)<br>
 
[Freshwaterecology.info](https://www.freshwaterecology.info/)<br>
 
<br>

#### Plancton : 
 
[Drive Plancton](https://drive.google.com/drive/u/2/folders/1gceOL5zb71uW0P9YylBLIdrEteCAD8Qg)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Général 
 
[Habitats-naturels.info](http://habitats-naturels.info/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Marin 
 
<br>

#### Général : 
 
[DORIS](https://doris.ffessm.fr/)<br>
 
[World Register of marine Species](https://www.marinespecies.org/photogallery.php)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Natura 2000 
 
[Evaluation de l'état de conservation](https://inpn.mnhn.fr/telechargement/documentation/natura2000/evaluation)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Phytosociologie 
 
[La Phytosociologie synusiale intégrée. Guide méthodologique](https://www.researchgate.net/publication/233773247_La_Phytosociologie_synusiale_integree_Guide_methodologique)<br>
 
[Site Guy Bouxin](http://guy-bouxin.e-monsite.com/)<br>
 
<br>

#### Outil : 
 
[Florass par RoZo](http://florass.zoom-ecologue.com/index.php)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Plateforme  {.tabset .tabset-fade}
 
<br>

### EEE 
 
<br>

#### Général : 
 
[NOBANIS](https://www.nobanis.org/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Général 
 
[Encyclopedia of Life](https://eol.org/)<br>
 
[Nature France](https://naturefrance.fr/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Sciences participatives 
 
<br>

#### Flore : 
 
[Herbonautes](http://lesherbonautes.mnhn.fr/)<br>
 
<br>

#### Général : 
 
[Participae](http://www.particitae.upmc.fr/fr/index.html)<br>
 
[Vigienature](https://www.vigienature.fr/)<br>
 
<br>

#### Oiseaux : 
 
[Oiseaux des jardins](https://www.oiseauxdesjardins.fr/)<br>
 
<br>

#### Pollinisateur : 
 
[SAPOLL](https://sapoll.eu/)<br>
 
[SPIPOLL](https://www.spipoll.org/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Référentiel  {.tabset .tabset-fade}
 
<br>

### Taxref 
 
[API Taxref](https://taxref.mnhn.fr/taxref-web/api/doc)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
# Eau {.tabset .tabset-fade .tabset-pills} 
 
<br>

## Zone humide  {.tabset .tabset-fade}
 
<br>

### Donnees 
 
[Prélocalisation nationale des zones humides (2023)](https://inpn.mnhn.fr/telechargement/cartes-et-information-geographique/mh/zh)<br>
 
[Réseau zone humide](http://sig.reseau-zones-humides.org/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
# Outils {.tabset .tabset-fade .tabset-pills} 
 
<br>

## Bibliographie  {.tabset .tabset-fade}
 
<br>

### Général 
 
[Dictionnaire encyclopédique de la diversité biologique et de la conservation de la nature](https://www.laccreteil.fr/spip.php?rubrique2)<br>
 
[Documentation IRD](https://horizon.documentation.ird.fr/exl-php/accueil)<br>
 
[OpenAIRE](https://explore.openaire.eu/)<br>
 
[Zenodo](https://zenodo.org)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Zotero 
 
[Zotero Styles](https://www.zotero.org/styles)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Données  {.tabset .tabset-fade}
 
<br>

### Faune 
 
<br>

#### Général : 
 
[Bibliothèque virtuelle numérique – Faune de France](https://faunedefrance.org/bibliotheque-virtuelle-numerique/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Général 
 
[Drive Natural-host](https://drive.google.com/drive/folders/1JiM9drwXFP6inyruDVzBAwRDGi330CDC?usp=sharing)<br>
 
[Eu-nomen](https://www.eu-nomen.eu/portal/index.php)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### SINP 
 
[Extraction ISNP](https://framaforms.org/formulaire-de-demande-dacces-aux-donnees-du-sinp-974-1485242721)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Geomatique  {.tabset .tabset-fade}
 
<br>

### Carte thématique 
 
[Light pollution map](https://lighttrends.lightpollutionmap.info/#zoom=0&lon=32.89298&lat=20.63642)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Composeur 
 
<br>

#### SVG : 
 
[Svgsilh : Base de donnees de formes SVG](https://svgsilh.com/fr/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Lizmap 
 
[Lizmap](https://www.3liz.com/lizmap.html)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Logiciel 
 
[Geoda Center](https://geodacenter.github.io/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Plateforme 
 
[Cadastre.gouv](https://www.cadastre.gouv.fr/scpc/accueil.do)<br>
 
[DicoGIS](https://static.geotribu.fr/articles/2014/art_2014-09-25_dicogis/#presentation-de-loutil)<br>
 
[DoGeo](https://blog.dogeo.fr/)<br>
 
[DoGeo projection](https://app.dogeo.fr/Projection/#/point-to-coords)<br>
 
[Eau France](https://www.eaufrance.fr/)<br>
 
[Géo data gouv](https://geo.data.gouv.fr/fr/)<br>
 
[Geofoncier](https://www.geofoncier.fr/)<br>
 
[Géoservices IGN](https://geoservices.ign.fr/services-web)<br>
 
[Geotribu](https://static.geotribu.fr/)<br>
 
[IGN : remonter le temps](https://remonterletemps.ign.fr/comparer/basic?x=55.465501&y=-20.887779&z=17&layer1=ORTHOIMAGERY.ORTHOPHOTOS&layer2=ORTHOIMAGERY.ORTHOPHOTOS.1950-1965&mode=doubleMap)<br>
 
[INPN inspire](https://inpn-inspire.mnhn.fr/catalogue/srv/fre/catalog.search#/search)<br>
 
[PeiGeo](http://peigeo.re/)<br>
 
[Peps](https://peps.cnes.fr)<br>
 
[Risques naturels (PPR)](http://www.risquesnaturels.re/)<br>
 
[Sandre Eau France](https://www.sandre.eaufrance.fr/atlas/srv/fre/catalog.search#/home)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Qfield 
 
[Qfield](https://qfield.org/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Qgis 
 
<br>

#### Tutoriel : 
 
[Docs Qgis](https://docs.qgis.org/3.10/fr/docs/index.html)<br>
 
[Naturagis](https://naturagis.fr)<br>
 
[Qgis tutirials](http://www.qgistutorials.com/fr/index.html)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Methodologie  {.tabset .tabset-fade}
 
<br>

### Organisation 
 
[Mutibao](http://www.multibao.org/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Terrain 
 
[Outils collecte information / suivi de biodiversite](https://professionnels.ofb.fr/sites/default/files/pdf/documentation/TIC2015_CENLR-CENPACA-FONEXP-CNRS-CEFE-outils_nomades.pdf)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## News  {.tabset .tabset-fade}
 
<br>

### Emplois 
 
[Emploi-territorial](https://www.emploi-territorial.fr/)<br>
 
[Réseau TEE](https://www.reseau-tee.net/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Flore 
 
[Le Plantoscope](https://leplantoscope.fr/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Media 
 
[Actu environnement](https://www.actu-environnement.com/)<br>
 
[Conservation Nature](https://www.conservation-nature.fr/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## R  {.tabset .tabset-fade}
 
<br>

### Cartographie 
 
[Rcarto](https://rcarto.github.io/carto_avec_r/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Cheatsheet 
 
[ggplot 2](https://thinkr.fr/pdf/ggplot2-french-cheatsheet.pdf)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### DiagrammR 
 
[DiagrammR](https://cyberhelp.sesync.org/blog/visualization-with-diagrammeR.html)<br>
 
[Doc DiagrammR](https://rich-iannone.github.io/DiagrammeR/graphviz_and_mermaid.html)<br>
 
[Mermaid doc](https://mermaid-js.github.io/mermaid/#/)<br>
 
[Mermaid editor](https://mermaid-js.github.io/mermaid-live-editor/edit/)<br>
 
[Qastack Gantt charts with R](https://qastack.fr/programming/3550341/gantt-charts-with-r)<br>
 
[Rstudio Graphviz and DiagrammR](https://www.rstudio.com/blog/rstudio-v0-99-preview-graphviz-and-diagrammer/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### R markdown 
 
[Bookdown](https://bookdown.org/)<br>
 
[Cheatsheet Flextable](https://ardata-fr.github.io/flextable-book/assets/pdf/cheat_sheet_flextable.pdf)<br>
 
[Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/)<br>
 
[Flextable book](https://ardata-fr.github.io/flextable-book/)<br>
 
[Flextable David Gohel](https://davidgohel.github.io/flextable/reference/index.html)<br>
 
[Flextable Gallery](https://ardata-fr.github.io/flextable-gallery/gallery/)<br>
 
[Lecon R markdown](https://rmarkdown.rstudio.com/lesson-1.html)<br>
 
[Markdown tables](https://www.tablesgenerator.com/markdown_tables)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Shiny 
 
[Shiny example](https://github.com/aagarw30/R-Shinyapp-Tutorial)<br>
 
[Shiny Rstudio tutorial](https://shiny.rstudio.com/tutorial/)<br>
 
[Shiny sur serveur AWS](https://www.charlesbordet.com/fr/guide-shiny-aws/#a-quoi-s-attendre-dans-ce-guide)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Statistiques 
 
[Tidymodel](https://www.tidymodels.org/learn/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Tutoriel 
 
[R pour statophobe](https://perso.univ-rennes1.fr/denis.poinsot/Statistiques_%20pour_statophobes/R%20pour%20les%20statophobes.pdf)<br>
 
[Tuto R : stt4230](https://stt4230.rbind.io/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Recherche  {.tabset .tabset-fade}
 
<br>

### IA 
 
[Chat GPT](https://chat.openai.com/)<br>
 
[You](https://you.com/)<br>
 
[NA](https://www.futurepedia.io/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Taxonomie  {.tabset .tabset-fade}
 
<br>

### Général 
 
[Lifemap](https://lifemap-ncbi.univ-lyon1.fr/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Identification 
 
<br>

#### Général : 
 
[Identificationkey](https://identificationkey.fr/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### TAXREF 
 
[Taxref-match](https://taxref.mnhn.fr/taxref-match/taxrefmatch/import)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Xper 3 
 
[Xper 3](https://www.xper3.fr/?language=fr)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Vulgarisation  {.tabset .tabset-fade}
 
<br>

### Général 
 
[Biodiville](http://www.biodiville.org/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### ONF 
 
[La forêt méditerranéenne vue par un écureuil](https://www.onf.fr/vivre-la-foret/+/add::la-foret-mediterraneene-en-image.html)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Youtube 
 
<br>

#### Flore : 
 
[Le chemin de la nature](https://www.youtube.com/c/LeChemindelaNature-LaCha%C3%AEne)<br>
 
<br>

#### Général : 
 
[Augustin Soulard – Youtube](https://www.youtube.com/@augustinsoulard)<br>
 
[La Minute nature – Youtube](https://www.youtube.com/channel/UCkph5f42oWLXN09Kf-XbBMQ)<br>
 
[Marie Wild – Youtube](https://www.youtube.com/channel/UCI7DUjUYcPOLZ0pRuk4klkw)<br>
 
[Salamandre - Youtube](https://www.youtube.com/user/EditionsSalamandre)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
# Pays {.tabset .tabset-fade .tabset-pills} 
 
<br>

## Belgique  {.tabset .tabset-fade}
 
<br>

### Flore 
 
[Biodiversité Wallonie](http://biodiversite.wallonie.be/fr/accueil.html?IDC=6)<br>
 
[L’herbier en image – Belgique](https://www.herbierimages.be/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Norvège  {.tabset .tabset-fade}
 
<br>

### Général 
 
[artsdatabanken.no](https://www.artsdatabanken.no/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Suède  {.tabset .tabset-fade}
 
<br>

### Général 
 
[artfakta.se](https://artfakta.se/artinformation?lang=sv)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Suisse  {.tabset .tabset-fade}
 
<br>

### Flore 
 
[Infloflora](https://wiki.infoflora.ch/swissflorawiki/fr/FloraWiki_-_le_wiki_sur_la_flore_suisse)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Tchéquie  {.tabset .tabset-fade}
 
<br>

### Général 
 
[Biolib.cz](https://www.biolib.cz/en/main/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
# Régions {.tabset .tabset-fade .tabset-pills} 
 
<br>

## Auvergne  {.tabset .tabset-fade}
 
<br>

### Blog 
 
[Photos araignées, insectes, fleurs](https://auvergne-fleurs-insectes-araignees.blogspot.com/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Bretagne  {.tabset .tabset-fade}
 
<br>

### Faune 
 
[Faune Bretagne – LPO](https://www.faune-bretagne.org/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Général 
 
[Bretagne vivante](https://www.bretagne-vivante.org/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Centre-Val-de-loire  {.tabset .tabset-fade}
 
<br>

### Général 
 
[FNE Centre-Val-de-Loire](https://fne-centrevaldeloire.org/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Guyane  {.tabset .tabset-fade}
 
<br>

### Rizière 
 
[Plantes rizières Guyane Cirad](http://plantes-rizieres-guyane.cirad.fr/generalites)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Ile-de-France  {.tabset .tabset-fade}
 
<br>

### Insectes 
 
[Cettia](https://cettia.fr/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Massif central  {.tabset .tabset-fade}
 
<br>

### Faune&Flore 
 
[Faune & Flore du Massif Central](https://www.fauneflore-massifcentral.fr/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Mayotte  {.tabset .tabset-fade}
 
<br>

### Gestion & restauration 
 
<br>

#### Pépinière : 
 
[Pépinière Mayotte de plans indigènes](http://www.achats-responsables-mayotte.org/structure/pot-concept/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Nouvelle-Aquitaine  {.tabset .tabset-fade}
 
<br>

### Général 
 
[Sauvages du Poitou](https://www.sauvagesdupoitou.com/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Occitanie  {.tabset .tabset-fade}
 
<br>

### Flore 
 
<br>

#### Pyrénées : 
 
[La flore des pyrénées](http://www.lafloredespyrenees.fr/pagefamille.html)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Général 
 
[Afleurdepau](http://www.afleurdepau.com/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## PACA  {.tabset .tabset-fade}
 
<br>

### Alpes-de-Haute-Provence 
 
<br>

#### Flore : 
 
[Atlas Flore 04](https://www.atlasflore04.org/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Réunion  {.tabset .tabset-fade}
 
<br>

### Associations 
 
[Nature Océan Indien](https://natureoceanindien.org/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Données 
 
[Open data Réunion](https://data.regionreunion.com/pages/accueil/)<br>
 
[StatFlore](https://biotopeoi.shinyapps.io/statfore/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Eau 
 
[SDAGE 2022 - 2027](http://www.comite-eau-biodiversite-reunion.fr/le-sdage-2022-2027-est-adopte-a207.html)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Faune 
 
[Faune Réunion](https://www.faune-reunion.fr/index.php?m_id=1#)<br>
 
<br>

#### Insectes : 
 
[Insectarium La Réunion](http://insectarium-reunion.fr/)<br>
 
<br>

#### Mollusques : 
 
[Mollusque de l’île de la Réunion](http://vieoceane.free.fr/mollusques/intro_mollusque.htm)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Flore 
 
[Borbonica](https://www.borbonica.re/)<br>
 
[Mi aime a ou - Flore](https://www.mi-aime-a-ou.com/flore_ile_reunion.php)<br>
 
[Plantnet Réunion](https://identify.plantnet.org/fr/reunion/species)<br>
 
[Zinvaziv](https://zinvaziv.re/)<br>
 
<br>

#### Orchidées : 
 
[Orchidées Vandes](http://orchidees.vandes.com/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Gestion & restauration 
 
<br>

#### Flore : 
 
[DAUPI](https://daupi.cbnm.org/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Milieu Marin 
 
<br>

#### Acoustique : 
 
[Lucy - Ocean Sonics Resources](https://sites.google.com/a/oceansonics.com/ocean-sonics-resource-site/Current-Releases/lucy)<br>
 
<br>

#### Biodiversité : 
 
[BORBONICA](https://www.borbonica.re/)<br>
 
[Corals of the world](http://www.coralsoftheworld.org/page/home/)<br>
 
[Coraux de La Réunion - Univ](http://coraux.univ-reunion.fr/spip.php?article35)<br>
 
[Fishbase](https://www.fishbase.se/search.php)<br>
 
[Map mondial recif corallien](https://resourcewatch.org/data/explore?section=Discover&selectedCollection=&zoom=3&lat=-8.92848706266558&lng=57.56835937499995&pitch=0&bearing=0&basemap=dark&labels=light&layers=%255B%257B%2522dataset%2522%253A%25226acb7469-29b4-4712-8254-8c130314337b%2522%252C%2522opacity%2522%253A1%252C%2522layer%2522%253A%2522c39c9ff7-632a-4f94-a748-1a9cd9649ed6%2522%257D%255D&aoi=&page=1&sort=most-viewed&sortDirection=-1)<br>
 
[Marine Ecological Research Management Aid](https://datamermaid.org/)<br>
 
[NOAA Coral Reef Watch](https://coralreefwatch.noaa.gov/product/vs/timeseries/western_indian_ocean.php)<br>
 
[WORMS](http://www.marinespecies.org/aphia.php?p=taxdetails&id=219014)<br>
 
<br>

#### Conditions marines : 
 
[Données stations météos](http://www.meteor-oi.re/index.php/observations-meteorologiques/le-reseau-climatologique/)<br>
 
[Marées SHOM](https://maree.shom.fr/harbor/POINTE_DES_GALETS/hlt/0?date=2021-10-19&utc=4)<br>
 
[Pluviométrie](https://www.m-r.li/mtofrbul/compil_carte_observation_mf_10_jours.php)<br>
 
[Windy](https://www.windy.com/?-21.100,55.600,5)<br>
 
<br>

#### Données milieu marin : 
 
[ATLAS DCE](http://envlit.ifremer.fr/var/envlit/storage/documents/atlas_DCE/Reunion/RUN/carte)<br>
 
[Plateforme milieu marin France](https://oceans-indien-austral.milieumarinfrance.fr/)<br>
 
[Référentiel Habitats marins](https://inpn.mnhn.fr/habitat/cd_typo/26)<br>
 
[Sextant](https://sextant.ifremer.fr/ocean-indien)<br>
 
[SURVAL](https://wwz.ifremer.fr/surval/)<br>
 
<br>

#### SIG : 
 
[Allen Coral Atlas](https://allencoralatlas.org/atlas/#6.64/-21.2085/56.2301)<br>
 
[Bathymétrie mondiale](https://portal.emodnet-bathymetry.eu/)<br>
 
[Carto ZEE Mondiale](https://www.marineregions.org/)<br>
 
[PeiGeo](http://peigeo.re/)<br>
 
<br>

#### Technique : 
 
[Coral Restauration Database](https://www.icriforum.org/restoration/coral-restoration-database/)<br>
 
[Protocole prélèvements hydro](https://prelevements-hydro.ifremer.fr/presentation.html)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Reptiles 
 
[Nature Ocean Idien - Reptiles](https://natureoceanindien.org/Reptiles-reunion/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Suisse  {.tabset .tabset-fade}
 
<br>

### Faune 
 
<br>

#### Oiseaux : 
 
[Vogewarte](https://www.vogelwarte.ch/fr/oiseaux/jeu/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
# Réglementaire {.tabset .tabset-fade .tabset-pills} 
 
<br>

## Code de l'environnement  {.tabset .tabset-fade}
 
<br>

### Etude d'impact 
 
[Etude d'impact ou cas par cas ?](https://www.legifrance.gouv.fr/codes/section_lc/LEGITEXT000006074220/LEGISCTA000006108640/#LEGISCTA000006108640)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Général 
 
[Code de l'environnement legifrance](https://www.legifrance.gouv.fr/codes/section_lc/LEGITEXT000006074220/LEGISCTA000006108631/#LEGISCTA000006108631)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Risques  {.tabset .tabset-fade}
 
<br>

### Georisques 
 
[Géorisques](https://www.georisques.gouv.fr/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
# Structure {.tabset .tabset-fade .tabset-pills} 
 
<br>

## Association  {.tabset .tabset-fade}
 
<br>

### Bretagne 
 
<br>

#### Ille-et-Vilaine : 
 
[Cercle Naturaliste des Etudiants Rennais](https://cerclenaturalisteetudiants.wordpress.com/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Centre-Val-de-Loire 
 
<br>

#### Loiret : 
 
[Société pour le Muséum d’Orléans et les Sciences (So.MOS)](https://somosorleans.org/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### France 
 
<br>

#### Général : 
 
[Aspas-nature](https://www.aspas-nature.org/)<br>
 
[Fédération Française des Sociétés de Sciences Naturelles](https://faunedefrance.org/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Général 
 
[Carte Naturalistes des Terres](https://naturalistesdesterres.gogocarto.fr/map#/carte/@47.36,2.65,5z?cat=all)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Occitanie 
 
<br>

#### Général : 
 
[Natureo](https://www.natureo.org/)<br>
 
<br>

#### SBOCC : 
 
[Calendrier SBOCC](https://sbocc.fr/calendrier/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### PACA 
 
[Agenda CEN PACA](https://cen-paca.org/participer/agenda/)<br>
 
[LPO – FAUNE PACA](https://www.faune-paca.org/index.php?m_id=20006)<br>
 
<br>

#### Bouches-du-Rhônes (13) : 
 
[Société Linnéenne de Provence](https://www.linneenne-provence.org/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Bureau d'étude  {.tabset .tabset-fade}
 
<br>

### MTDA 
 
[Agence MTDA](https://www.mtda.fr/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## CBN  {.tabset .tabset-fade}
 
<br>

### Documents 
 
[CBN Massif Central](https://portail-documentaire.cbnmc.fr/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

### Général 
 
[CBN Alpin](https://www.cbn-alpin.fr/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## DREAL  {.tabset .tabset-fade}
 
<br>

### PACA 
 
[DREAL PACA](https://www.paca.developpement-durable.gouv.fr/thematiques-r3158.html)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
<br>

## Réserve  {.tabset .tabset-fade}
 
<br>

### PACA 
 
<br>

#### Bouches-du-Rhônes (13) : 
 
[La Tour du Valat](https://tourduvalat.centredoc.fr/)<br>
 

 
 ------------------------------- 
 

 
 ------------------------------- 
 
